apiVersion: apps/v1
kind: Deployment
metadata:
  name: talking-lands-app
  namespace: nodejs-app
  labels:
    app: talking-lands-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: talking-lands-app
  template:
    metadata:
      labels:
        app: talking-lands-app
    spec:
      containers:
      - name: alking-lands-app
        image: <DOCKERHUB_USERNAME>/talking-lands-app:latest
        ports:
        - containerPort: 3000
