apiVersion: v1
kind: Service
metadata:
  name: talking-lands-app-service
  namespace: nodejs-app
spec:
  selector:
    app: talking-lands-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
