name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies and run tests
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t <docker_image>:latest .
          docker push <docker_image>:latest

  deploy-to-k8s:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml

      # Verify deployment
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/nodejs-app

  rollback:
    needs: deploy-to-k8s
    if: failure()
    runs-on: ubuntu-latest
    steps:
      # Rollback deployment
      - name: Rollback Kubernetes Deployment
        run: |
          kubectl rollout undo deployment/nodejs-app
